{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zrenderer.fullname" . }}-cfm
data:
  {{- range $key, $value := .Values.configMap.configMapData }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
  {{- end }}
{{- end }}
