{{- if .Values.ingress.enabled -}}
{{- $fullName := include "website.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.customHttpErrors }}
    nginx.ingress.kubernetes.io/custom-http-errors: {{ .Values.ingress.customHttpErrors -}}
    {{- end }}
    {{- if .Values.ingress.maxUploadSize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.maxUploadSize | quote -}}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
